apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooks-extension
  namespace: tekton-pipelines
  labels:
    app: webhooks-extension
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhooks-extension
  template:
    metadata:
      labels:
        app: webhooks-extension
    spec:
      serviceAccountName: tekton-webhooks-extension
      containers:
        - name: webhooks-extension
          image: webhooksExtensionImage
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
          env:
          - name: PORT
            value: "8080"
          - name: INSTALLED_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: DOCKER_REGISTRY_LOCATION
            value: DOCKER_REPO
          - name: WEB_RESOURCES_DIR
            value: web

          # Set GIT_SSL_VERIFICATION_ENABLED to "false" if your Git server has a self-signed HTTPS certificate. 
          # Caution! Doing this leaves you potentially vulnerable to systems impersonating your Git server 
          - name: GIT_SSL_VERIFICATION_ENABLED
            value: "true"

          # WEBHOOK_CALLBACK_URL is the value of the endpoint that Git will deliver webhooks to. 
          # Exposed via a Route or Ingress; needs to be set at install time. 
          - name: WEBHOOK_CALLBACK_URL
            value: "http://listener.IPADDRESS.nip.io"

          # Set WEBHOOK_SSL_VERIFICATION_ENABLED to "true" if the Route or Ingress in front of WEBHOOK_CALLBACK_URL is protected
          # by an HTTPS endpoint signed by a certificate that your Git server accepts. 
          - name: WEBHOOK_SSL_VERIFICATION_ENABLED
            value: "false"

          - name: SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName