apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-webhooks-extension-minimal
  namespace: tekton-pipelines
rules:
- apiGroups:
  - route.openshift.io
  resources:
  -  routes
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - patch